### ISSUE TITLE
Group by time is different ?

### ISSUE THREAD

**Issue by Seqway** [MrDrache333/iobroker-tankerkoenig-grafana-dashboard#2]
Hello,

one question when I go through the dashboard I realise that under

CHEAPEST --> WHERE $timeFilter GROUP BY time **(5m)** fill(none)

MOST EXPENSIVE --> WHERE $timeFilter GROUP BY time **(7d)** fill(none)

If I understand it correctly it should be shown what is the most expensive or cheapest value the last 7 days or ?
Is this then correct ?

**Comment by Seqway** [comment]
I See that you made it via Query Options ?
Doesnt it affect it each other ?

<img width="503" alt="image" src="https://user-images.githubusercontent.com/40624961/210137558-97a72798-b5c1-4dbb-8fe5-16d91c081e7e.png">

**Comment by MrDrache333** [comment]
That should have no impact at all, because you still use the max/min. Value in the last 7days as set in the Query Options. If you want to display a graph, then it would make a difference because the Query witht the GROUP BY 5m will return much more Datapoints than the query with GROUP BY 7d, which will return just one.

But to optimize performance you could just let the 7d in the query options and the Query itself and change it to the same for the 5m Query.

Hope that makes it clear :)
